"""rename auth_id to sub

Revision ID: 8645c892b9a0
Revises: 13f4dcfe3742
Create Date: 2024-11-27 18:36:30.032001

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8645c892b9a0"
down_revision: Union[str, None] = "13f4dcfe3742"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "class_enrollments", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.alter_column(
        "classes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "content_blocks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "courses", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "lessons", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.add_column("progress", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )

    op.alter_column("users", "auth_id", new_column_name="sub")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "auth_id", new_column_name="sub")
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("progress", "created_at")
    op.alter_column(
        "lessons", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "courses", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "content_blocks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "classes", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("class_enrollments", "created_at")

    # ### end Alembic commands ###
